"""Añadir campos de cliente a tabla sales

Revision ID: 0866cb4978c7
Revises: 0acfba2a2698
Create Date: 2025-10-26 01:27:19.997732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0866cb4978c7'
down_revision: Union[str, Sequence[str], None] = '0acfba2a2698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- ARREGLO: Tachamos (comentamos) estas líneas ---
    # Estas líneas intentaban borrar una tabla que aún no existía.
    # op.drop_index(op.f('ix_work_order_notes_id'), table_name='work_order_notes')
    # op.drop_table('work_order_notes')
    # --- FIN DEL ARREGLO ---

    op.add_column('sales', sa.Column('customer_ci', sa.String(), nullable=False))
    op.add_column('sales', sa.Column('customer_name', sa.String(), nullable=False))
    op.add_column('sales', sa.Column('customer_phone', sa.String(), nullable=False))
    op.add_column('sales', sa.Column('customer_address', sa.String(), nullable=False))
    op.add_column('sales', sa.Column('customer_email', sa.String(), nullable=False))
    op.create_index(op.f('ix_sales_customer_ci'), 'sales', ['customer_ci'], unique=False)
    op.create_index(op.f('ix_sales_customer_name'), 'sales', ['customer_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_customer_name'), table_name='sales')
    op.drop_index(op.f('ix_sales_customer_ci'), table_name='sales')
    op.drop_column('sales', 'customer_email')
    op.drop_column('sales', 'customer_address')
    op.drop_column('sales', 'customer_phone')
    op.drop_column('sales', 'customer_name')
    op.drop_column('sales', 'customer_ci')
    
    # --- ARREGLO: Tachamos (comentamos) estas líneas ---
    # op.create_table('work_order_notes',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    # sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('work_order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('work_order_notes_user_id_fkey')),
    # sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('work_order_notes_work_order_id_fkey')),
    # sa.PrimaryKeyConstraint('id', name=op.f('work_order_notes_pkey'))
    # )
    # op.create_index(op.f('ix_work_order_notes_id'), 'work_order_notes', ['id'], unique=False)
    # --- FIN DEL ARREGLO ---
    
    # ### end Alembic commands ###
