"""agregar_firma_cliente_ordenes

Revision ID: 09767eb98948
Revises: 564c86dc4579
Create Date: 2026-01-23 22:34:51.531064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09767eb98948'
down_revision: Union[str, Sequence[str], None] = '564c86dc4579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_orders', sa.Column('customer_signature', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_orders', 'customer_signature')
    # ### end Alembic commands ###
