"""Corregir campo nulo en customer_declined_check de work_orders

Revision ID: 0acfba2a2698
Revises: 52c5a276a25a
Create Date: 2025-10-22 22:29:29.364527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0acfba2a2698'
down_revision: Union[str, Sequence[str], None] = '52c5a276a25a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_orders', 'customer_declined_check',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_orders', 'customer_declined_check',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
