"""Implementar sistema de cuentas y transacciones de caja

Revision ID: 0b7fae60ca83
Revises: 5f34e03c02a5
Create Date: 2025-10-18 01:40:49.873698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b7fae60ca83'
down_revision: Union[str, Sequence[str], None] = '5f34e03c02a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_accounts_id'), 'cash_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_cash_accounts_name'), 'cash_accounts', ['name'], unique=True)
    op.create_table('cash_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['cash_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_transactions_id'), 'cash_transactions', ['id'], unique=False)
    op.drop_index(op.f('ix_expense_logs_id'), table_name='expense_logs')
    op.drop_table('expense_logs')
    op.drop_index(op.f('ix_cash_box_sessions_id'), table_name='cash_box_sessions')
    op.drop_table('cash_box_sessions')
    op.add_column('sales', sa.Column('payment_method_details', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'payment_method_details')
    op.create_table('cash_box_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('initial_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('final_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('cash_box_sessions_location_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('cash_box_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cash_box_sessions_pkey'))
    )
    op.create_index(op.f('ix_cash_box_sessions_id'), 'cash_box_sessions', ['id'], unique=False)
    op.create_table('expense_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('expense_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('expense_logs_pkey'))
    )
    op.create_index(op.f('ix_expense_logs_id'), 'expense_logs', ['id'], unique=False)
    op.drop_index(op.f('ix_cash_transactions_id'), table_name='cash_transactions')
    op.drop_table('cash_transactions')
    op.drop_index(op.f('ix_cash_accounts_name'), table_name='cash_accounts')
    op.drop_index(op.f('ix_cash_accounts_id'), table_name='cash_accounts')
    op.drop_table('cash_accounts')
    # ### end Alembic commands ###
