"""agregar campos sri a ventas

Revision ID: 2a7fd2d86090
Revises: 70d7ed27209e
Create Date: 2026-01-26 04:50:21.889185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a7fd2d86090'
down_revision: Union[str, Sequence[str], None] = '70d7ed27209e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('sri_access_key', sa.String(), nullable=True))
    op.add_column('sales', sa.Column('sri_auth_status', sa.String(), nullable=True))
    op.add_column('sales', sa.Column('sri_auth_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sales', sa.Column('sri_xml_path', sa.String(), nullable=True))
    op.add_column('sales', sa.Column('sri_error_message', sa.String(), nullable=True))
    op.create_index(op.f('ix_sales_sri_access_key'), 'sales', ['sri_access_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_sri_access_key'), table_name='sales')
    op.drop_column('sales', 'sri_error_message')
    op.drop_column('sales', 'sri_xml_path')
    op.drop_column('sales', 'sri_auth_date')
    op.drop_column('sales', 'sri_auth_status')
    op.drop_column('sales', 'sri_access_key')
    # ### end Alembic commands ###
