"""agregar location a clientes

Revision ID: 2eae83eac343
Revises: 274ce7e80bbb
Create Date: 2025-12-08 14:49:52.058054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eae83eac343'
down_revision: Union[str, Sequence[str], None] = '274ce7e80bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customers', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'location_id')
    # ### end Alembic commands ###
