"""agregar_atributos_producto

Revision ID: 300813591b1e
Revises: adf3a7234cd5
Create Date: 2026-01-23 01:25:02.469064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '300813591b1e'
down_revision: Union[str, Sequence[str], None] = 'adf3a7234cd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('products', sa.Column('model', sa.String(), nullable=True))
    op.add_column('products', sa.Column('color', sa.String(), nullable=True))
    op.add_column('products', sa.Column('compatibility', sa.String(), nullable=True))
    op.add_column('products', sa.Column('condition', sa.String(), nullable=True))
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_products_model'), 'products', ['model'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_model'), table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_column('products', 'condition')
    op.drop_column('products', 'compatibility')
    op.drop_column('products', 'color')
    op.drop_column('products', 'model')
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###
