"""vincular_gastos_caja_orden

Revision ID: 35274c0dd9ef
Revises: 37c6bfbbeb92
Create Date: 2026-01-01 17:46:36.160316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35274c0dd9ef'
down_revision: Union[str, Sequence[str], None] = '37c6bfbbeb92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
