"""add_expense_account_and_order

Revision ID: 37c6bfbbeb92
Revises: da818bd882bb
Create Date: 2026-01-01 17:27:52.241188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37c6bfbbeb92'
down_revision: Union[str, Sequence[str], None] = 'da818bd882bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('account_id', sa.Integer(), nullable=True))
    op.add_column('expenses', sa.Column('work_order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expenses', 'work_orders', ['work_order_id'], ['id'])
    op.create_foreign_key(None, 'expenses', 'cash_accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'work_order_id')
    op.drop_column('expenses', 'account_id')
    # ### end Alembic commands ###
