"""Add transfer reception

Revision ID: 3ae5c5a0e325
Revises: cece29f43c4e
Create Date: 2026-01-20 21:18:53.967364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ae5c5a0e325'
down_revision: Union[str, Sequence[str], None] = 'cece29f43c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_items', sa.Column('received_quantity', sa.Integer(), nullable=True))
    op.add_column('transfer_items', sa.Column('reception_note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer_items', 'reception_note')
    op.drop_column('transfer_items', 'received_quantity')
    # ### end Alembic commands ###
