"""add_public_ids

Revision ID: 3bcb18b18918
Revises: e09113220d27
Create Date: 2026-01-04 14:06:04.155258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bcb18b18918'
down_revision: Union[str, Sequence[str], None] = 'e09113220d27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('public_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_sales_public_id'), 'sales', ['public_id'], unique=True)
    op.add_column('work_orders', sa.Column('public_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_work_orders_public_id'), 'work_orders', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_orders_public_id'), table_name='work_orders')
    op.drop_column('work_orders', 'public_id')
    op.drop_index(op.f('ix_sales_public_id'), table_name='sales')
    op.drop_column('sales', 'public_id')
    # ### end Alembic commands ###
