"""agregar daily_goal a locations

Revision ID: 4d03eb2fbbe2
Revises: e7eb682c0d39
Create Date: 2026-01-19 01:39:41.125174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d03eb2fbbe2'
down_revision: Union[str, Sequence[str], None] = 'e7eb682c0d39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
