"""Añadir campos detallados y fotos a ordenes de trabajo

Revision ID: 52c5a276a25a
Revises: 08a11bc430b2
Create Date: 2025-10-22 21:56:52.200121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52c5a276a25a'
down_revision: Union[str, Sequence[str], None] = '08a11bc430b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_order_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_order_images_id'), 'work_order_images', ['id'], unique=False)
    op.add_column('work_orders', sa.Column('device_unlock_pattern', sa.String(), nullable=True))
    op.add_column('work_orders', sa.Column('device_account', sa.String(), nullable=True))
    op.add_column('work_orders', sa.Column('device_account_password', sa.String(), nullable=True))
    op.add_column('work_orders', sa.Column('device_initial_check', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('work_orders', sa.Column('customer_declined_check', sa.Boolean(), nullable=True))
    op.drop_column('work_orders', 'device_physical_state')
    op.drop_column('work_orders', 'device_initial_state')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_orders', sa.Column('device_initial_state', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('work_orders', sa.Column('device_physical_state', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('work_orders', 'customer_declined_check')
    op.drop_column('work_orders', 'device_initial_check')
    op.drop_column('work_orders', 'device_account_password')
    op.drop_column('work_orders', 'device_account')
    op.drop_column('work_orders', 'device_unlock_pattern')
    op.drop_index(op.f('ix_work_order_images_id'), table_name='work_order_images')
    op.drop_table('work_order_images')
    # ### end Alembic commands ###
