"""Hacer opcionales email, telefono y direccion en la tabla sales

Revision ID: 53e52b67b40f
Revises: fd96e3b3675a
Create Date: 2025-10-30 18:59:31.866202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53e52b67b40f'
down_revision: Union[str, Sequence[str], None] = 'fd96e3b3675a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'customer_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sales', 'customer_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sales', 'customer_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'customer_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sales', 'customer_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sales', 'customer_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
