"""agregar cascade delete a ventas

Revision ID: 564c86dc4579
Revises: cb84ffa7e4d7
Create Date: 2026-01-23 22:04:16.404042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '564c86dc4579'
down_revision: Union[str, Sequence[str], None] = 'cb84ffa7e4d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_orders', 'customer_signature_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_orders', sa.Column('customer_signature_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
