"""reglas_unicas_productos_clientes

Revision ID: 5e7ee262ca52
Revises: 199cf3744b30
Create Date: 2026-01-16 23:03:21.970487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e7ee262ca52'
down_revision: Union[str, Sequence[str], None] = '199cf3744b30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_id_card_company_uc', 'customers', ['id_card', 'company_id'])
    op.create_unique_constraint('_sku_company_uc', 'products', ['sku', 'company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_sku_company_uc', 'products', type_='unique')
    op.drop_constraint('_id_card_company_uc', 'customers', type_='unique')
    # ### end Alembic commands ###
