"""add_location_hierarchy

Revision ID: 65f949caa3fa
Revises: 3ae5c5a0e325
Create Date: 2026-01-20 23:09:56.491274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65f949caa3fa'
down_revision: Union[str, Sequence[str], None] = '3ae5c5a0e325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
