"""Regla unica para nombre de caja por sucursal

Revision ID: 669a36c28528
Revises: c46f66ac7146
Create Date: 2025-11-05 19:48:24.189980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '669a36c28528'
down_revision: Union[str, Sequence[str], None] = 'c46f66ac7146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Borramos la regla vieja (que el nombre sea único en TODA la tabla)
    # Usamos el nombre exacto que vimos en el error: "ix_cash_accounts_name"
    op.drop_index('ix_cash_accounts_name', table_name='cash_accounts')

    # 2. Creamos la nueva regla (que el nombre + sucursal sean únicos)
    # Usamos el nombre que definimos en models.py: "_cash_account_name_location_uc"
    op.create_unique_constraint('_cash_account_name_location_uc', 'cash_accounts', ['name', 'location_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Borramos la nueva regla (nombre + sucursal)
    op.drop_constraint('_cash_account_name_location_uc', 'cash_accounts', type_='unique')

    # 2. Volvemos a crear la regla vieja (solo nombre)
    op.create_index('ix_cash_accounts_name', 'cash_accounts', ['name'], unique=True)

    # ### end Alembic commands ###
