"""add_phone_email_to_locations

Revision ID: 688e687b69a6
Revises: 0a3d4ceecf26
Create Date: 2025-12-29 14:36:36.777415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '688e687b69a6'
down_revision: Union[str, Sequence[str], None] = '0a3d4ceecf26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'email')
    op.drop_column('locations', 'phone')
    # ### end Alembic commands ###
