"""agregar is_distributor a company

Revision ID: 6987afbc3d27
Revises: 81a5b6901fa2
Create Date: 2026-01-15 22:49:13.357516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6987afbc3d27'
down_revision: Union[str, Sequence[str], None] = '81a5b6901fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('is_distributor', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'is_distributor')
    # ### end Alembic commands ###
