"""agregar campos factura electronica sri

Revision ID: 70d7ed27209e
Revises: fcf9a6aea471
Create Date: 2026-01-26 04:26:01.747072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70d7ed27209e'
down_revision: Union[str, Sequence[str], None] = 'fcf9a6aea471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_settings', sa.Column('sri_env', sa.String(), nullable=True))
    op.add_column('company_settings', sa.Column('sri_signature_path', sa.String(), nullable=True))
    op.add_column('company_settings', sa.Column('sri_signature_password', sa.String(), nullable=True))
    op.add_column('company_settings', sa.Column('sri_establishment_code', sa.String(), nullable=True))
    op.add_column('company_settings', sa.Column('sri_emission_point_code', sa.String(), nullable=True))
    op.add_column('company_settings', sa.Column('is_electronic_billing_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_settings', 'is_electronic_billing_active')
    op.drop_column('company_settings', 'sri_emission_point_code')
    op.drop_column('company_settings', 'sri_establishment_code')
    op.drop_column('company_settings', 'sri_signature_password')
    op.drop_column('company_settings', 'sri_signature_path')
    op.drop_column('company_settings', 'sri_env')
    # ### end Alembic commands ###
