"""agregar warranty_terms

Revision ID: 75a077f9f7e1
Revises: 4e665d18d147
Create Date: 2025-12-31 14:53:48.953774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75a077f9f7e1'
down_revision: Union[str, Sequence[str], None] = '4e665d18d147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('warranty_terms', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'warranty_terms')
    # ### end Alembic commands ###
