"""add_physical_condition

Revision ID: 75f8d27950f1
Revises: 87595466569c
Create Date: 2025-12-25 17:38:53.307374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75f8d27950f1'
down_revision: Union[str, Sequence[str], None] = '87595466569c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_orders', sa.Column('physical_condition', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_orders', 'physical_condition')
    # ### end Alembic commands ###
