"""agregar_demo_frozen_at_a_company

Revision ID: 81258462056b
Revises: 2a7fd2d86090
Create Date: 2026-01-26 17:41:27.834618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81258462056b'
down_revision: Union[str, Sequence[str], None] = '2a7fd2d86090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('demo_frozen_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'demo_frozen_at')
    # ### end Alembic commands ###
