"""agregar recovery code

Revision ID: 81a5b6901fa2
Revises: a8df049caad6
Create Date: 2026-01-15 02:44:53.329237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81a5b6901fa2'
down_revision: Union[str, Sequence[str], None] = 'a8df049caad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('recovery_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'recovery_code')
    # ### end Alembic commands ###
