"""Hacer columnas de cliente NOT NULL

Revision ID: 92d2f21907fd
Revises: 1d64c9b6c9d0
Create Date: 2025-10-26 01:35:10.426856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d2f21907fd'
down_revision: Union[str, Sequence[str], None] = '1d64c9b6c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'customer_ci',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sales', 'customer_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'customer_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sales', 'customer_ci',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
