"""fix_notification_rules_company222

Revision ID: a8df049caad6
Revises: 0e3ac7161ed7
Create Date: 2026-01-15 00:36:14.018601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8df049caad6'
down_revision: Union[str, Sequence[str], None] = '0e3ac7161ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_rules', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notification_rules', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification_rules', type_='foreignkey')
    op.drop_column('notification_rules', 'company_id')
    # ### end Alembic commands ###
