"""agregar_ciclo_facturacion

Revision ID: adf3a7234cd5
Revises: e224e8e9236b
Create Date: 2026-01-22 21:47:45.599085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adf3a7234cd5'
down_revision: Union[str, Sequence[str], None] = 'e224e8e9236b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('next_payment_due', sa.DateTime(timezone=True), nullable=True))
    op.add_column('companies', sa.Column('last_payment_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'last_payment_date')
    op.drop_column('companies', 'next_payment_due')
    # ### end Alembic commands ###
