"""Añadir columna address a locations

Revision ID: b25a088bdea2
Revises: 53e52b67b40f
Create Date: 2025-11-01 16:47:35.540144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b25a088bdea2'
down_revision: Union[str, Sequence[str], None] = '53e52b67b40f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'address')
    # ### end Alembic commands ###
