"""agregar daily_goal a locations

Revision ID: b28a5fdd37b2
Revises: 5e7ee262ca52
Create Date: 2026-01-19 01:26:52.455109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b28a5fdd37b2'
down_revision: Union[str, Sequence[str], None] = '5e7ee262ca52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('daily_goal', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'daily_goal')
    # ### end Alembic commands ###
