"""agregar_tipo_producto

Revision ID: cb84ffa7e4d7
Revises: 300813591b1e
Create Date: 2026-01-23 01:45:42.325332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb84ffa7e4d7'
down_revision: Union[str, Sequence[str], None] = '300813591b1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_type', sa.String(), nullable=True))
    op.create_index(op.f('ix_products_product_type'), 'products', ['product_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_product_type'), table_name='products')
    op.drop_column('products', 'product_type')
    # ### end Alembic commands ###
