"""agregar_company_id_a_todo

Revision ID: cd20a9cf7252
Revises: 2d8db659c7da
Create Date: 2026-01-15 00:22:14.054211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd20a9cf7252'
down_revision: Union[str, Sequence[str], None] = '2d8db659c7da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_accounts', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cash_accounts', 'companies', ['company_id'], ['id'])
    op.add_column('categories', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_foreign_key(None, 'categories', 'companies', ['company_id'], ['id'])
    op.add_column('customers', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_customers_id_card'), table_name='customers')
    op.create_index(op.f('ix_customers_id_card'), 'customers', ['id_card'], unique=False)
    op.create_foreign_key(None, 'customers', 'companies', ['company_id'], ['id'])
    op.add_column('expense_categories', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_expense_categories_name'), table_name='expense_categories')
    op.create_index(op.f('ix_expense_categories_name'), 'expense_categories', ['name'], unique=False)
    op.create_foreign_key(None, 'expense_categories', 'companies', ['company_id'], ['id'])
    op.add_column('expenses', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expenses', 'companies', ['company_id'], ['id'])
    op.add_column('locations', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'locations', 'companies', ['company_id'], ['id'])
    op.add_column('products', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_foreign_key(None, 'products', 'companies', ['company_id'], ['id'])
    op.add_column('sales', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales', 'companies', ['company_id'], ['id'])
    op.add_column('suppliers', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_foreign_key(None, 'suppliers', 'companies', ['company_id'], ['id'])
    op.add_column('work_orders', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'work_orders', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_orders', type_='foreignkey')
    op.drop_column('work_orders', 'company_id')
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=True)
    op.drop_column('suppliers', 'company_id')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'company_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.drop_column('products', 'company_id')
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_column('locations', 'company_id')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'company_id')
    op.drop_constraint(None, 'expense_categories', type_='foreignkey')
    op.drop_index(op.f('ix_expense_categories_name'), table_name='expense_categories')
    op.create_index(op.f('ix_expense_categories_name'), 'expense_categories', ['name'], unique=True)
    op.drop_column('expense_categories', 'company_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_id_card'), table_name='customers')
    op.create_index(op.f('ix_customers_id_card'), 'customers', ['id_card'], unique=True)
    op.drop_column('customers', 'company_id')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.drop_column('categories', 'company_id')
    op.drop_constraint(None, 'cash_accounts', type_='foreignkey')
    op.drop_column('cash_accounts', 'company_id')
    # ### end Alembic commands ###
