"""crear_modulo_gastos

Revision ID: da818bd882bb
Revises: 72f115b6149e
Create Date: 2026-01-01 15:27:19.683801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da818bd882bb'
down_revision: Union[str, Sequence[str], None] = '72f115b6149e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Añadimos server_default='0' para rellenar los productos viejos con 0
    op.add_column('products', sa.Column('average_cost', sa.Float(), nullable=False, server_default='0'))
    # Añadimos server_default='0' para rellenar las ventas viejas con 0
    op.add_column('sale_items', sa.Column('recorded_cost', sa.Float(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_items', 'recorded_cost')
    op.drop_column('products', 'average_cost')
    # ### end Alembic commands ###
