"""Añadir campos de RRHH a la tabla users

Revision ID: e0458f562488
Revises: b25a088bdea2
Create Date: 2025-11-01 18:41:35.925415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0458f562488'
down_revision: Union[str, Sequence[str], None] = 'b25a088bdea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('id_card', sa.String(), nullable=True))
    op.add_column('users', sa.Column('emergency_contact', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'emergency_contact')
    op.drop_column('users', 'id_card')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
