"""agregar_config_whatsapp

Revision ID: e09113220d27
Revises: 35274c0dd9ef
Create Date: 2026-01-04 10:58:34.832189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e09113220d27'
down_revision: Union[str, Sequence[str], None] = '35274c0dd9ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_settings', sa.Column('whatsapp_country_code', sa.String(), nullable=True))
    op.add_column('company_settings', sa.Column('whatsapp_default_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_settings', 'whatsapp_default_message')
    op.drop_column('company_settings', 'whatsapp_country_code')
    # ### end Alembic commands ###
