"""Añadí más campos a la orden de trabajo y también el estado de la orden de trabajo.

Revision ID: e4466dceea3a
Revises: 771664daa4dc
Create Date: 2025-10-12 21:50:02.330181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4466dceea3a'
down_revision: Union[str, Sequence[str], None] = '771664daa4dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_orders', sa.Column('device_password', sa.String(), nullable=True))
    op.add_column('work_orders', sa.Column('device_physical_state', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.alter_column('work_orders', 'customer_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('work_orders', 'customer_id_card',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('work_orders', 'customer_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('work_orders', 'device_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('work_orders', 'device_brand',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('work_orders', 'device_model',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('work_orders', 'estimated_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_orders', 'estimated_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('work_orders', 'device_model',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('work_orders', 'device_brand',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('work_orders', 'device_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('work_orders', 'customer_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('work_orders', 'customer_id_card',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('work_orders', 'customer_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('work_orders', 'device_physical_state')
    op.drop_column('work_orders', 'device_password')
    # ### end Alembic commands ###
