"""agregar horarios a notificaciones

Revision ID: e49a87994cfd
Revises: 9cca612fe4a4
Create Date: 2025-12-02 12:46:38.646590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e49a87994cfd'
down_revision: Union[str, Sequence[str], None] = '9cca612fe4a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_rules', sa.Column('schedule_times', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_rules', 'schedule_times')
    # ### end Alembic commands ###
