"""Añadir image_url a productos

Revision ID: e4e2dbfff4b0
Revises: 0b7fae60ca83
Create Date: 2025-10-21 17:05:11.964905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4e2dbfff4b0'
down_revision: Union[str, Sequence[str], None] = '0b7fae60ca83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=True))
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('work_orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('work_orders', 'reported_issue',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('work_orders', 'deposit_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_orders', 'deposit_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('work_orders', 'reported_issue',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('work_orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###
