"""agregar daily_goal a locations

Revision ID: e7eb682c0d39
Revises: b28a5fdd37b2
Create Date: 2026-01-19 01:36:08.290113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7eb682c0d39'
down_revision: Union[str, Sequence[str], None] = 'b28a5fdd37b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
