"""add whatsapp work order message

Revision ID: f8586825a782
Revises: 3bcb18b18918
Create Date: 2026-01-09 19:51:56.633539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8586825a782'
down_revision: Union[str, Sequence[str], None] = '3bcb18b18918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_settings', sa.Column('whatsapp_work_order_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_settings', 'whatsapp_work_order_message')
    # ### end Alembic commands ###
